    <footer>
      <div class="row">
        <div class="col-md-12">
          <hr/>
          <p>Copyright &copy; 2016 The Godot Engine community - MIT Licensed - <a href="https://github.com/godotengine/asset-library">GitHub repository</a>.</p>
        </div>
      </div>
    </footer>
  </div>

  <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
  <!-- Include all compiled plugins (below), or include individual files as needed -->
  <script src="<?php echo $bowerpath ?>/bootstrap/dist/js/bootstrap.min.js"></script>
</body>

</html>
