<?php include("_header.phtml") ?>

<div class="asset-search-container">
    <form method="get" action="edit">
        <div class="input-group">
            <input type="text" class="form-control" name="filter" placeholder="Search for..." value="<?php if(isset($params['filter'])) echo esc($params['filter']) ?>">
            <span class="input-group-btn">
                <button class="btn btn-primary" type="submit">Search</button>
            </span>
        </div>

        <div class="form-inline form-search">
            <div class="form-group">
                <label>Status</label>
                <?php foreach($constants['edit_status'] as $id => $status) if(is_int($id)) { ?>
                    <label class="form-checkbox">
                        <input type="checkbox" name="status[<?php echo esc($status) ?>]" value="1"
                            <?php if(isset($params['status']) && (is_array($params['status']) ?
                                isset($params['status'][$status]) && $params['status'][$status] :
                                in_array($status, explode(' ', $params['status'])))
                            ) echo 'checked=""';
                            ?>>
                        <?php echo esc(ucfirst(str_replace('_', ' ', $status))) ?>
                    </label>
                <?php } ?>
            </div>

            <?php if(isset($params['asset'])) { ?>
                <div class="form-group bg-info form-highlighted">
                    <label class="form-checkbox">
                        <input type="checkbox" name="asset" value="<?php echo esc($params['asset']) ?>" checked="">
                        <?php if($params['asset'] == -1) { ?>
                            Only new assets
                        <?php } else { ?>
                            Only asset #<?php echo esc($params['asset']) ?>
                        <?php } ?>
                    </label>
                </div>
            <?php } ?>

            <?php if(isset($params['user'])) { ?>
                <div class="form-group bg-info form-highlighted">
                    <label class="form-checkbox">
                        <input type="checkbox" name="user" value="<?php echo esc($params['user']) ?>" checked="">
                        Only by <?php echo esc($params['user']) ?>
                    </label>
                </div>
            <?php } ?>
        </div>
    </form>

    <div class="asset-search-results">
        <ol class="asset-list moderation-list">
            <?php foreach($data['result'] as $i => $asset_edit) { ?>
                <li class="asset-item">
                    <a href="<?php echo raw($basepath) . '/asset/edit/' . url($asset_edit['edit_id']) ?>" class="asset-header">
                        <img class="media-object" src="<?php echo esc($asset_edit['icon_url']) ?>" alt="<?php echo esc($asset_edit['title']) ?>'s icon" width=80 height=80>
                        <div class="asset-title">
                            <h4><?php echo esc($asset_edit['title']) ?></h4>
                            <div class="asset-tags-container">
                                <div class="asset-tags">
                                    <span class="label label-info"><?php echo raw(ucfirst(str_replace('_', ' ', $asset_edit['godot_version']))) ?></span>
                                    <span class="label label-<?php echo raw([
                                        'official' => 'danger',
                                        'community' => 'success',
                                        'testing' => 'default',
                                    ][$asset_edit['support_level']]) ?>"><?php echo raw(ucfirst($asset_edit['support_level'])) ?></span>
                                </div>
                            </div>
                            <div class="asset-tags-container asset-tags-moderation">
                                <div class="asset-tags">
                                    <span class="label label-default"><?php echo raw($asset_edit['author']) ?></span>
                                    <span class="label label-<?php echo raw([
                                        'new' => 'info',
                                        'in_review' => 'primary',
                                        'rejected' => 'danger',
                                        'accepted' => 'success'
                                    ][$asset_edit['status']]) ?>"><?php echo raw(ucfirst(str_replace('_', ' ', $asset_edit['status']))) ?></span>
                                </div>
                            </div>
                        </div>
                    </a>
                    <?php if($asset_edit['status'] == 'rejected' && $asset_edit['reason']) { ?>
                        <div class="asset-footer">
                            <div>
                                <span><b>Rejection reason:</b></span><br>
                                <span><?php echo esc($asset_edit['reason']) ?></span>
                            </div>
                        </div>
                    <?php } ?>
                </li>
            <?php } ?>
        </ol>

        <?php include("_pagination.phtml") ?>
    </div>
</div>

<?php include("_footer.phtml") ?>
