<?php include("_header.phtml") ?>
<div class="media">
    <div class="media-left">
        <img class="media-object" src="<?php echo esc($data['icon_url']) ?>" alt="<?php echo esc($data['title']) ?>'s icon" width="80" height="80">
    </div>
    <div class="media-body">
        <h4 class="media-heading">
           <?php echo esc($data['title']) ?>
        </h4>
        <div class="asset-tags" style="margin: 8px 0;">
            <span class="label label-primary"><?php echo esc($data['category']) ?></span>
            <span class="label label-info"><?php echo esc(ucfirst(str_replace('_', ' ', $data['godot_version']))) ?></span>
            <span class="label label-<?php echo raw([
                'official' => 'danger',
                'community' => 'success',
                'testing' => 'default',
            ][$data['support_level']]) ?>"><?php echo esc(ucfirst($data['support_level'])) ?></span>
            <span class="label label-default"><?php echo esc($data['cost']) ?></span>
            <?php if ($data['searchable'] == 0) { ?>
                <span class="label label-default">Hidden</span>
            <?php } ?>
        </div>
        <p class="text-muted">
            <b><?php echo esc($data['version_string']) ?></b> | <?php echo esc(explode(" ", $data['modify_date'])[0]) ?> by
            <a href="<?php echo raw($basepath) ?>/asset?user=<?php echo esc($data['author']) ?>" title="Search assets by '<?php echo esc($data['author']) ?>'"><?php echo esc($data['author']) ?></a>
        </p>
    </div>
</div>
<hr/>
<p><?php echo nl2br(esc($data['description']), false) ?></p>
<hr/>
<div class="asset-links">
    <a class="btn btn-primary" href="<?php echo esc($data['browse_url']) ?>">
        <i class="glyphicon glyphicon-folder-open"></i>&nbsp; View files
    </a>
    <a class="btn btn-primary" href="<?php echo esc($data['download_url']) ?>">
        <i class="glyphicon glyphicon-download"></i> Download
    </a>
    <?php if($data['issues_url'] != "") { ?>
        <a class="btn btn-primary" href="<?php echo esc($data['issues_url']) ?>">
            <i class="glyphicon glyphicon-check"></i> Submit an issue
        </a>
    <?php } ?>
    <a class="btn btn-default" href="<?php echo raw($basepath) ?>/asset/edit?asset=<?php echo url($data['asset_id']) ?>&amp;status=new+in_review+accepted+rejected">
        <i class="glyphicon glyphicon-list"></i> Recent Edits
    </a>
</div>
<div class="asset-tools">
    <?php if (isset($user) && (($user['type'] >= $constants['user_type']['editor']) || $user['user_id'] === $data['author_id'])) : ?>
        <div class="panel panel-danger">
            <div class="panel-heading">
                Author tools
            </div>
            <div class="panel-body">
                <?php if ($data['searchable'] == 1) { ?>
                    <form class="form" action="<?php echo raw($basepath) ?>/asset/<?php echo url($data['asset_id']) ?>/delete" method="post">
                        <?php include("_csrf.phtml") ?>
                        <p>The asset is currently <b>visible</b> in the library.</p>
                        <hr>
                        <div class="flex-container">
                            <button type="submit" class="btn btn-danger" onclick="return window.confirm('Do you really want to hide this asset?');">
                                <i class="glyphicon glyphicon-eye-close"></i> Hide in library
                            </button>
                            <a class="btn btn-success" href="<?php echo raw($basepath) ?>/asset/<?php echo url($data['asset_id']) ?>/edit">
                                <i class="glyphicon glyphicon-pencil"></i> Edit asset
                            </a>
                        </div>
                    </form>
                <?php } else { ?>
                    <form class="form" action="<?php echo raw($basepath) ?>/asset/<?php echo url($data['asset_id']) ?>/undelete" method="post">
                        <?php include("_csrf.phtml") ?>
                        <p>The asset is currently <b>hidden</b> in the library.</p>
                        <hr>
                        <div class="flex-container">
                            <button type="submit" class="btn btn-warning" onclick="return window.confirm('Do you want to restore this asset?');">
                                <i class="glyphicon glyphicon-eye-open"></i> Restore to library
                            </button>
                            <a class="btn btn-success" href="<?php echo raw($basepath) ?>/asset/<?php echo url($data['asset_id']) ?>/edit">
                                <i class="glyphicon glyphicon-pencil"></i> Edit asset
                            </a>
                        </div>
                    </form>
                <?php } ?>
            </div>
        </div>
    <?php endif ?>
    <?php if(isset($user) && ($user['type'] >= $constants['user_type']['moderator'])) { ?>
        <div class="panel panel-danger">
            <div class="panel-heading">
                Admin tools
            </div>
            <div class="panel-body">
                <form class="form" action="<?php echo raw($basepath) ?>/asset/<?php echo url($data['asset_id']) ?>/support_level" method="post">
                    <?php include("_csrf.phtml") ?>
                    <p><label for="support_level">Support level</label></p>
                    <div class="flex-container">
                        <select id="support_level" name="support_level" class="form-control">
                            <?php foreach($constants['support_level'] as $id => $name) if(is_int($id)) { ?>
                                <option value="<?php echo esc($name) ?>" <?php if($name == $data['support_level']) echo 'selected=""'; ?>>
                                    <?php echo esc(ucfirst($name)) ?>
                                </option>
                            <?php } ?>
                        </select>
                        <button type="submit" class="btn btn-default">Change</button>
                    </div>
                </form>
            </div>
        </div>
    <?php } ?>
</div>
<hr/>
<div class="row">
    <?php foreach($data['previews'] as $key => $preview) { ?>
        <div class="col-xs-6 col-md-4 col-lg-3 text-center">
            <a href="<?php echo esc($preview['link']) ?>" target="_blank" class="thumbnail">
                <?php if($preview['type'] == 'image') { ?>
                    <img src="<?php echo esc($preview['link']) ?>" width="100%"/>
                <?php } else { ?>
                    <img src="<?php echo esc($preview['thumbnail']) ?>" width="100%"/>
                    <div class="btn btn-primary btn-lg" style="position: absolute; top: 50%; left: 50%; transform:translate(-50%,-50%); opacity: 0.8;">
                        <i class="glyphicon glyphicon-play" style="font-size:2em"></i>
                    </div>
                <?php } ?>
            </a>
        </div>
    <?php } ?>
</div>
<?php include("_footer.phtml") ?>
