<?php include("_header.phtml") ?>
<div class="row">
  <?php foreach($data['result'] as $i => $asset) { ?>
    <div class="col-md-6">
      <div class="media">
        <div class="media-left">
          <a href="<?php echo raw($basepath) . '/asset/' . url($asset['asset_id']) ?>">
            <img class="media-object" src="<?php echo esc($asset['icon_url']) ?>" alt="<?php echo esc($asset['title']) ?>'s icon" width=80 height=80>
          </a>
        </div>
        <div class="media-body">
          <h4 class="media-heading">
            <a href="<?php echo raw($basepath) . '/asset/' . url($asset['asset_id']) ?>"><?php echo esc($asset['title']) ?></a>
            <small><?php echo esc($asset['version_string']) ?></small>
            <?php for ($star=1; $star <= 5; $star++) { ?>
              <i class="glyphicon glyphicon-star<?php if($asset['rating'] < $star) echo '-empty'; ?>"></i>
            <?php } ?>
            <span class="label label-primary"><?php echo esc($asset['category']) ?></span>
            <span class="label label-<?php echo raw([
              'official' => 'success',
              'community' => 'info',
              'testing' => 'default',
            ][$asset['support_level']]) ?>"><?php echo esc(ucfirst($asset['support_level'])) ?></span>
          </h4>

          <p>Submitted by user <?php echo esc($asset['author']) ?>; <?php echo esc($asset['cost']) ?></p>
        </div>
      </div>
    </div>
  <?php } ?>
</div>
<?php include("_footer.phtml") ?>
