<?php include("_header.phtml") ?>
<div class="media">
  <div class="media-left">
    <img class="media-object" src="<?php echo htmlspecialchars($data['icon_url']) ?>" alt="<?php echo htmlspecialchars($data['title']) ?>'s icon" width=80 height=80>
  </div>
  <div class="media-body">
    <h4 class="media-heading">
      <?php echo htmlspecialchars($data['title']) ?>
      <small><?php echo htmlspecialchars($data['version_string']) ?></small>
      <?php for ($star=1; $star <= 5; $star++) { ?>
        <i class="glyphicon glyphicon-star<?php if($data['rating'] < $star) echo '-empty'; ?>"></i>
      <?php } ?>
      <span class="label label-primary"><?php echo htmlspecialchars($data['category']) ?></span>
      <span class="label label-<?php echo htmlspecialchars([
        'official' => 'success',
        'community' => 'info',
        'testing' => 'default',
      ][$data['support_level']]) ?>"><?php echo htmlspecialchars(ucfirst($data['support_level'])) ?></span>
    </h4>

    <p class="text-muted">Submitted by user <?php echo htmlspecialchars($data['author']) ?>; <?php echo htmlspecialchars($data['cost']) ?></p>
    <p>
      <?php echo $data['description'] ?>
    </p>
    <hr/>
    <p>
      <a class="btn btn-default" href="<?php echo $data['browse_url'] ?>">
        <i class="glyphicon glyphicon-folder-open"></i> View files
      </a>
      <a class="btn btn-primary" href="<?php echo $data['download_url'] ?>">
        <i class="glyphicon glyphicon-download"></i> Download
      </a>
      <?php if(isset($user)) { ?>
        <a class="btn btn-success" href="<?php echo $basepath ?>/asset/<?php echo $data['asset_id'] ?>/edit">
          <i class="glyphicon glyphicon-pencil"></i> Edit
        </a>
      <?php } ?>
      <a class="btn btn-warning" href="<?php echo $basepath ?>/asset/edit?asset=<?php echo $data['asset_id'] ?>&amp;status=accepted+rejected">
        <i class="glyphicon glyphicon-list"></i> Recent Edits
      </a>
    </p>
    <p class="text-muted">Sha256 Hash: <code><?php echo $data['download_hash'] ?></code></p>
    <hr/>
  </div>
</div>
<div class="row">
  <?php foreach($data['previews'] as $key => $preview) { ?>
    <div class="col-xs-6 col-md-4 col-lg-3 text-center">
      <a href="<?php echo $preview['link'] ?>" target="_blank" class="thumbnail">
        <?php if($preview['type'] == 'image') { ?>
          <img src="<?php echo $preview['link'] ?>" width="100%"/>
        <?php } else { ?>
            <img src="<?php echo $preview['thumbnail'] ?>" width="100%"/>
            <div class="btn btn-primary btn-lg" style="position: absolute; top: 50%; left: 50%; transform:translate(-50%,-50%); opacity: 0.8;">
              <i class="glyphicon glyphicon-play" style="font-size:2em"></i>
            </div>
        <?php } ?>
      </a>
    </div>
    <?php } ?>
</div>
<?php include("_footer.phtml") ?>
