<?php include("_header.phtml") ?>


<?php if(isset($data['error'])) { ?>
  <div class="alert alert-danger" role="alert"><b>Error: </b> <?php echo esc($data['error']) ?></div>
<?php } ?>

<form action="<?php echo raw($basepath) ?>/change_password" method="post">
  <?php include("_csrf.phtml") ?>
  <div class="form-group">
    <label for="new_password">Old password:</label>
    <input type="password" name="old_password" class="form-control" id="old_password" placeholder="Current password">
  </div>
  <div class="form-group">
    <label for="new_password">New password:</label>
    <input type="password" name="new_password" class="form-control" id="new_password" placeholder="Password">
  </div>
  <div class="btn-group">
    <button type="submit" class="btn btn-primary">Change password and logout</button>
  </div>
</form>
<?php include("_footer.phtml") ?>
