<?php include("_header.phtml") ?>
<?php $_asset_values = $data ?>
<form class="form-horizontal" action="<?php echo raw($basepath) ?>/asset/<?php echo url($data['asset_id']) ?>" method="post">
        <?php include("_csrf.phtml") ?>
        <fieldset>
                <!-- Form Name -->
                <legend>
                    Edit Asset
                    <a class="btn btn-default btn-sm" href="<?php echo raw($basepath) ?>/asset/<?php echo url($data['asset_id']) ?>">
                        Back
                    </a>
                </legend>

                <?php include("_asset_fields.phtml") ?>

                <div class="form-group">
                        <label class="col-md-4 control-label" for="submit"></label>
                        <div class="col-md-4">
                                <button id="submit" class="btn btn-primary">Submit edit</button>
                                <a class="btn btn-default" href="<?php echo raw($basepath) ?>/asset/<?php echo url($data['asset_id']) ?>">
                                    Cancel
                                </a>
                        </div>
                </div>

                <div class="form-group">
                    <div class="col-md-4 col-md-push-9 align-right">
                        <form action="<?php echo raw($basepath) ?>/asset/<?php echo url($data['asset_id']) ?>/delete" method="POST">
                            <input type="submit" id="delete" class="btn btn-danger" onclick="javascript:if(window.confirm('Do you really want to delete this asset?')){ return true; }else{ return false; }" value="Delete asset from library">
                        </form>
                    </div>
                </div>
        </fieldset>
</form>
<?php include("_footer.phtml") ?>
