<?php include("_header.phtml") ?>
<?php foreach($data['events'] as $i => $event) { ?>
    <div class="media"> <!-- TODO: Get real feed from @alketii -->
        <div class="media-left">

            <i class="glyphicon glyphicon-<?php echo raw([
                'new' => 'unchecked text-default',
                'in_review' => 'check text-primary',
                'rejected' => 'remove text-danger',
                'accepted' => 'ok text-success'][$event['status']])
            ?>" style="font-size:30px"></i>
        </div>
        <div class="media-body">
            <h4 class="media-heading">
                <span><?php echo ($event['asset_id'] == -1 ? 'Create ' : 'Edit ') ?></span>
                <a href="<?php echo raw($basepath) . '/asset/edit/' . url($event['edit_id']) ?>">"<?php echo esc($event['title']) ?>"</a>
                <span class="label label-<?php
                echo raw(['new' => 'info', 'in_review' => 'primary', 'rejected' => 'danger', 'accepted' => 'success'][$event['status']])
                ?>"><?php echo raw(ucfirst(str_replace('_', ' ', $event['status']))) ?></span>
            </h4>
            <?php if($event['reason']) echo 'Reason: ' . esc($event['reason']) ?>
        </div>
    </div>
<?php } ?>
<?php include("_footer.phtml") ?>
