<?php include("_header.phtml") ?>

<?php if(isset($user)) { ?>
  <div class="alert alert-info" role="alert">You are already logged in as <?php echo esc($user['username']) ?></div>
<?php } ?>

<form action="<?php echo raw($basepath) ?>/forgot_password" method="post">
  <?php include("_csrf.phtml") ?>
  <div class="form-group">
    <label for="login-form-email">Email</label>
    <input type="text" name="email" class="form-control" id="login-form-email" placeholder="Email">
  </div>
  <div class="btn-group">
    <button type="submit" class="btn btn-primary">Send reset link</button>
  </div>
</form>
<?php include("_footer.phtml") ?>
