<?php include("_header.phtml") ?>
<div class="row">
    <div class="col-md-3">
        <ul class="nav nav-pills nav-stacked">
            <li role="presentation"><a href="#">New Asset</a>
            <li role="presentation" class="active"><a href="#">SmaraGD</a>
            </li>
            <li role="presentation"><a href="#">Make Halo</a>
            </li>
            <li role="presentation"><a href="#">Unity2Godot</a>
            </li>
        </ul>
    </div>
    <div class="col-md-9">
        <div class="alert alert-info" role="alert">
            This asset is currently pending approval by our moderators. You will be notified by email when decision is made.
        </div>
        <form class="form-horizontal">
            <fieldset>

                <!-- Form Name -->
                <legend>Edit Asset</legend>

                <!-- Text input-->
                <div class="form-group">
                    <label class="col-md-4 control-label" for="asset_name">Asset Name</label>
                    <div class="col-md-5">
                        <input id="asset_name" name="asset_name" type="text" placeholder="Asset Name" class="form-control input-md" required="">
                        <span class="help-block">Set the name of your asset</span>
                    </div>
                </div>

                <!-- Select Basic -->
                <div class="form-group">
                    <label class="col-md-4 control-label" for="category">Category</label>
                    <div class="col-md-5">
                        <select id="category" name="category" class="form-control">
                            <option value="2d">2D</option>
                            <option value="3d">3D</option>
                            <option value="script">Script</option>
                            <option value="other">Other</option>
                        </select>
                    </div>
                </div>

                <!-- Text input-->
                <div class="form-group">
                    <label class="col-md-4 control-label" for="versiono">Version</label>
                    <div class="col-md-5">
                        <input id="versiono" name="versiono" type="text" placeholder="Version" class="form-control input-md" required="">
                        <span class="help-block">Set the version of your asset</span>
                    </div>
                </div>

                <!-- Text input-->
                <div class="form-group">
                    <label class="col-md-4 control-label" for="download">Download URL</label>
                    <div class="col-md-5">
                        <input id="download" name="download" type="text" placeholder="Download URL" class="form-control input-md" required="">
                        <span class="help-block">Set the URL to download the asset (direct)</span>
                    </div>
                </div>

                <!-- Select Basic -->
                <div class="form-group">
                    <label class="col-md-4 control-label" for="license">License</label>
                    <div class="col-md-5">
                        <select id="license" name="license" class="form-control">
                            <option value="MIT">MIT</option>
                            <option value="GPLv3">GPL v3</option>
                            <option value="GPLv2">GPL v2</option>
                            <option value="CC0">CC0</option>
                        </select>
                    </div>
                </div>

                <!-- Textarea -->
                <div class="form-group">
                    <label class="col-md-4 control-label" for="description">Description</label>
                    <div class="col-md-4">
                        <textarea class="form-control" id="description" name="description"></textarea>
                    </div>
                </div>

                <!-- File Button -->
                <div class="form-group">
                    <label class="col-md-4 control-label" for="icon">Icon</label>
                    <div class="col-md-4">
                        <input id="icon" name="icon" class="input-file" type="file">
                    </div>
                </div>

                <!-- File Button -->
                <div class="form-group">
                    <label class="col-md-4 control-label" for="screenshot1">Main Screenshot</label>
                    <div class="col-md-4">
                        <input id="screenshot1" name="screenshot1" class="input-file" type="file">
                    </div>
                </div>

                <!-- File Button -->
                <div class="form-group">
                    <label class="col-md-4 control-label" for="screenshot2">Screenshot 2</label>
                    <div class="col-md-4">
                        <input id="screenshot2" name="screenshot2" class="input-file" type="file">
                    </div>
                </div>

                <!-- File Button -->
                <div class="form-group">
                    <label class="col-md-4 control-label" for="filebutton">Screenshot 3</label>
                    <div class="col-md-4">
                        <input id="filebutton" name="filebutton" class="input-file" type="file">
                    </div>
                </div>

                <!-- File Button -->
                <div class="form-group">
                    <label class="col-md-4 control-label" for="screenshot4">Screenshot 4</label>
                    <div class="col-md-4">
                        <input id="screenshot4" name="screenshot4" class="input-file" type="file">
                    </div>
                </div>

                <!-- Text input-->
                <div class="form-group">
                    <label class="col-md-4 control-label" for="youtube">YouTube Link</label>
                    <div class="col-md-5">
                        <input id="youtube" name="youtube" type="text" placeholder="YouTube Link" class="form-control input-md">
                        <span class="help-block">Set the YouTube link demonstrating your asset</span>
                    </div>
                </div>

                <!-- Button -->
                <div class="form-group">
                    <label class="col-md-4 control-label" for="submit"></label>
                    <div class="col-md-4">
                        <button id="submit" name="submit" class="btn btn-primary">Edit</button>
                    </div>
                </div>

            </fieldset>
        </form>
    </div>
</div>
<?php include("_footer.phtml") ?>
