<?php include("_header.phtml") ?>
<form action="<?php echo $basepath ?>/register" method="post">
  <div class="form-group">
    <label for="login-form-username">Username</label>
    <input type="text" name="username" class="form-control" id="login-form-username" placeholder="Username">
  </div>
  <div class="form-group">
    <label for="login-form-email">Email</label>
    <input type="email" name="email" class="form-control" id="login-form-email" placeholder="Email">
  </div>
  <div class="form-group">
    <label for="login-form-password">Password</label>
    <input type="password" name="password" class="form-control" id="login-form-password" placeholder="Password">
  </div>
  <div class="btn-group">
    <button type="submit" class="btn btn-primary">Register</button>
    <a href="<?php echo $basepath ?>/login" class="btn btn-default">Login</a>
  </div>
</form>
<?php include("_footer.phtml") ?>
