<?php include("_header.phtml") ?>

<?php if(isset($user)): ?>
    <div class="alert alert-info" role="alert">Your are already logged in as <?php echo esc($user['username']) ?></div>
<?php endif ?>

<?php if(isset($data['error'])): ?>
    <div class="alert alert-danger" role="alert"><b>Error: </b> <?php echo esc($data['error']) ?></div>
<?php endif ?>

<form action="<?php echo raw($basepath) ?>/register" method="post">
    <?php include("_csrf.phtml") ?>
    <div class="form-group">
        <label for="login-form-username">Username</label>
        <input type="text" name="username" class="form-control" id="login-form-username" placeholder="Username">
    </div>
    <div class="form-group">
        <label for="login-form-email">Email</label>
        <input type="email" name="email" class="form-control" id="login-form-email" placeholder="Email">
    </div>
    <div class="form-group">
        <label for="login-form-password">Password</label>
        <input type="password" name="password" class="form-control" id="login-form-password" placeholder="Password">
    </div>
    <div class="btn-group">
        <a href="<?php echo raw($basepath) ?>/login" class="btn btn-default">Login</a>
        <button type="submit" class="btn btn-primary">Register</button>
    </div>
</form>
<?php include("_footer.phtml") ?>
