<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <title>Reset password for <?php echo $user['username'] ?> on Godot asset library</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  </head>
  <body>
    <h1>Password reset requested for Godot asset library</h1>
    <p>
      If you haven't requested the password reset you can disregard this email.
    </p>
    <p>
      If you aren't <?php echo htmlspecialchars($user['username']) ?>, you should disregard this email completely (or try to get in touch with the real <?php echo $user['username'] ?>, and forward it to him).
    </p>
    <p>
      <a href="<?php echo htmlspecialchars($link) ?>">Click this link to reset your password.</a>
      (In case it isn't working, you can type/copy this url manually: <?php echo htmlspecialchars($link) ?>)
    </p>
  </body>
</html>