<?php include("_header.phtml") ?>

<form action="<?php echo raw($basepath) ?>/reset_password" method="post">
    <?php include("_csrf.phtml") ?>
    <div class="form-group">
        <label for="new_password">New password for <?php if(isset($reset_user)) echo $reset_user['username'] ?></label>
        <input type="password" name="password" class="form-control" id="new_password" placeholder="Password">
    </div>
    <div class="btn-group">
        <button type="submit" class="btn btn-primary">Change password</button>
    </div>
</form>
<?php include("_footer.phtml") ?>
