<?php include("_header.phtml") ?>
<form class="form-horizontal" action="<?php echo raw($basepath) ?>/asset" method="post">
    <?php include("_csrf.phtml") ?>
        <fieldset>

                <!-- Form Name -->
                <legend>Submit Asset</legend>
                <p style="text-align:center">
                        Before submitting, please read the
                        <a href="https://docs.godotengine.org/en/latest/tutorials/assetlib/uploading_to_assetlib.html">
                        Submitting to the Asset Library</a> article for guidelines and instructions.
                </p>

                <?php include("_asset_fields.phtml") ?>

                <div class="form-group">
                        <label class="col-md-4 control-label" for="submit"></label>
                        <div class="col-md-4">
                                <button id="submit" class="btn btn-primary">Submit</button>
                        </div>
                </div>

        </fieldset>
</form>
<?php include("_footer.phtml") ?>
